### ISSUE TITLE
Maximum service records entries removal from config

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OamLog#159]
As per decision made on issue https://github.com/openBackhaul/ExecutionAndTraceLog/issues/165, can we also remove integer-profile from OAM log application, as we also use Elasticsearch for storing the logs in oamLog application and we have "max-docs" parameter in "elastic-search/service-record-policy" for configuring maximum entries allowed.

**Comment by openBackhaul** [comment]
Remove IntegerProfile from ProfileList
Remove instance of IntegerProfile from ProfileInstanceList
Remove all paths for managing IntegerProfile from OaM segment of OAS
Remove instance of IntegerProfile for number of records from CONFIGfile.

**Comment by openBackhaul** [comment]
Pull-request #160 merged.
