### ISSUE TITLE
OamRequestRecord schema : release-number pattern needs an update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OamLog#208]
Currently, the schema of OamRequestRecord has attribute "release-number" with pattern defined as **^([0-9]{1,2}).([0-9]{1,2}).([0-9]{1,2})$**, 
Problem statement:
A release-number is expected to be numbers separated by "."(dot). As per the current regex pattern, "." means it shall accept any character except line breaks. This allows application to accept release-number without "." as separator. example: 2/0/2 is accepted. 

Proposal: The pattern can be updated as **^([0-9]{1,2})\.([0-9]{1,2})\.([0-9]{1,2})$** (referred from release-number pattern of other services like /v1/regard-application). In this pattern "\." makes it to be strictly "."

**Comment by IswaryaaS** [comment]
similar issue https://github.com/openBackhaul/ExecutionAndTraceLog/issues/218

**Comment by openBackhaul** [comment]
Changed pattern to '^([0-9]{1,2})\\.([0-9]{1,2})\\.([0-9]{1,2})$'
