### ISSUE TITLE
Merge develop branch to main branch and create tag v2.0.1_impl, v2.0.1_test

### ISSUE THREAD

**Issue by sunil-kumar-meena** [openBackhaul/OamLog#266]
Merging develop to main branch

- [ ] Create pull request to merge develop branch to main branch
- [ ] Create a tag v2.0.1_impl with the following details of the open issues in the version 2.
- [ ] Create a tag v2.0.1_test for publishing the testsuites for version 2.

## Implementation of OamLog v2.0.1
This release contains,
-implementation of the individual services
-BasicServices incorporated from npm package onf-core-model-ap-bs+2.0.1-alpha.19
-Application pattern framework incorporated from npm package onf-core-model-ap+2.0.1-alpha.19

## Latest Acceptance TestReport
Software upgrade: 
Report timestamp : Tuesday, 11 July 2023 15:23:02
Total run Duration : 5m 16.6s
Average response time : 90ms
Total assertions : 1323
Total failures : 9
Total skipped test : nil

Individual report:
Report timestamp : Tuesday, 11 July 2023 14:39:27
Total run Duration : 1m 54.9s
Average response time : 63ms
Total assertions : 1836
Total failures : 3
Total skipped test : nil

## Open Issues :
https://github.com/openBackhaul/OamLog/issues/276
https://github.com/openBackhaul/OamLog/issues/277
https://github.com/openBackhaul/OamLog/issues/278
https://github.com/openBackhaul/OamLog/issues/279

## Assertion Failure report :
For the failures observed in the latest run , following are the issues created to resolve.
Apart from the open issues mentioned in the [open issues](#Open-Issues) others are resolved. 
Detailed information shall be found in the each mapped issue(in the comment starting with "Assertion failure details")

*Individual services*
|                   Issue Number                            | assertions failures   |
| --------------------------------------------------------- | -------------------   |
| https://github.com/openBackhaul/OamLog/issues/279         |          1            |
| https://github.com/openBackhaul/OamLog/issues/276         |          2            |

*Software upgrade*
|                   Issue Number                            | assertions failures   |
| --------------------------------------------------------- | -------------------   |
| https://github.com/openBackhaul/OamLog/issues/274         |          4            |
| https://github.com/openBackhaul/OamLog/issues/278         |          5            |

**Comment by vanithavalluripalli9** [comment]
This issue is closed as part of PR https://github.com/openBackhaul/OamLog/pull/280
