### ISSUE TITLE
bequeath-your-data-and-die is failing for OamLog

### ISSUE THREAD

**Issue by venkat-nallati** [openBackhaul/OamLog#270]
500 response code for bequeath-your-data-and-die.

Proposed code change:
New line: let forwardingAutomationInputList;
        if (logicalTerminationPointConfigurationStatus != undefined) {

          /****************************************************************************************
           * Prepare attributes to automate forwarding-construct
           ****************************************************************************************/
Updated line:          forwardingAutomationInputList = await prepareForwardingAutomation.bequeathYourDataAndDie(
            logicalTerminationPointConfigurationStatus
          );
          ForwardingAutomationService.automateForwardingConstructAsync(
            operationServerName,
            forwardingAutomationInputList,
            user,
            xCorrelator,
            traceIndicator,
            customerJourney
          );
        }
Updated line:       
      softwareUpgrade.upgradeSoftwareVersion(user, xCorrelator, traceIndicator, customerJourney, forwardingAutomationInputList.length)
        .catch(err => console.log(`upgradeSoftwareVersion failed with error: ${err}`));
New line:    }

Priority: low

**Comment by vanithavalluripalli9** [comment]
Changes related to this issue are merged with PR  https://github.com/openBackhaul/OamLog/pull/271

Hence , closing the issue.
