### ISSUE TITLE
Typo errors found in spec files

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OamLog#317]
- [x] As per decision made on https://github.com/openBackhaul/ApplicationPattern/issues/836, instances of _CurrentController shall be expected to be removed_ from specification files.
      - There are few occurrences of CurrentController instances in [forwardings.yaml](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bforwardings.yamll) and [config.json](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bconfig.json) file. These shall be removed.

- [x] In [forwardings.yaml](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bforwardings.yamll) and [config.json](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bconfig.json), in INPUT fc-port of forwarding-construct _ServiceRequestCausesLoggingRequest_, we shall need to add the following services.
     - ol-2-1-0-op-s-bm-013 - /v1/dispose-remainders-of-deregistered-application
     - ol-2-1-0-op-s-bm-014 - /v1/inform-about-preceding-release
     - ol-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release

- [x] Since, _/v1/update-client-of-subsequent-release_ could update ltp instances in load file, this shall be eligible for sending a LTP Update request to ALT. In forwarding-construct _ServiceRequestCausesLtpUpdateRequest_, /v1/update-client-of-subsequent-release (ol-2-1-0-op-s-bm-015) is to be added into INPUT fc-port list.
This change is required in both [forwardings.yaml](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bforwardings.yamll) and [config.json](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bconfig.json) files.

- [x] In [forwardings.yaml](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bforwardings.yamll) and [config.json](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bconfig.json) files, forwarding _ServiceRequestCausesLtpDeletionRequest_, we shall need to add the operation-server uuid of /v1/disregard-application -- ol-2-1-0-op-s-is-002 as it is responsible for deleting ltp instances in load file.

- [x] In [config.json](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bconfig.json), _ol-2-1-0-op-s-bs-000_ is listed twice in client-ltp list of ol-2-1-0-http-s-000. One instance shall be removed for avoiding duplicate entries. 

- [x] In [config.json](https://github.com/openBackhaul/OamLog/blob/develop/spec/OamLog%2Bconfig.json), the application-name value of ol-2-1-0-http-c-or-2-0-1-000 shall be updated as "OamLog" instead of "OldRelease"

**Comment by openBackhaul** [comment]
Also item 4) covered as requested.
