### ISSUE TITLE
Load file : detailed-logging-is-on attribute to be removed from logical-termination-point instances

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OamLog#41]
As per understanding, detailed-logging-is-on attribute is applicable only for the operation "/v1/record-service-request" of ExecutionAndTraceLog

Problem Description:
In load-file, [OamLog_0.0.2_tsi.211217.1745+data.2.json](https://github.com/openBackhaul/OamLog/blob/develop/OamLog_0.0.2_tsi.211217.1745%2Bdata.2.json),  for ltp instance ol-0-0-1-op-c-2040  contains an additional attribute _detailed-logging-is-on_, which needs to be removed.

Note : 
- ol-0-0-1-op-c-2040 refers to  /v1/redirect-oam-request-information

Related issues:
https://github.com/openBackhaul/ApplicationLayerTopology/issues/63
https://github.com/openBackhaul/AdministratorAdministration/issues/40
https://github.com/openBackhaul/OperationKeyManagement/issues/32
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/47

**Comment by openBackhaul** [comment]
Done
