### ISSUE TITLE
server: oam-record-profile uuid to be updated 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OamLog#47]
As per issue https://github.com/openBackhaul/OamLog/issues/4, the uuid pattern is decided to be updated from ^ol-0-0-1-oam-record-p-\d{4}$ to ^ol-0-0-1-oam-record-p-\d{6}$.

Problem statement:
As per the decision, the server-side code is updated to create oam-record-profile entries having uuid(s) with 6 digits. 
This tends to be problem when there is a difference in server-code and /api/openApi.yaml file in server

proposal 1: Update server-logic to create 4-digit uuid suffix 
proposal 2: Update api/openapi.yaml file for uuid pattern of oam-record-profile to have ^ol-0-0-1-oam-record-p-\d{6}$

**Comment by PrathibaJee** [comment]
Issue resolved by the changes delivered in the PullRequest https://github.com/openBackhaul/OamLog/pull/48. Hence closing the issue.
