### ISSUE TITLE
Updating the UUIDs of FCs

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OamLog#77]
Process for updating the UUIDs of FCs

- [x] Katharina to update fc-uuid in CONFIGfile and OAS wherever applicable referencing from ForwardingList on feature branch
- [x] Katharina to create pull request from feature branch
- [x] Iswaryaa to review the pull request
If no errors found
- [x] Iswaryaa to Approve the pull request
- [x] Iswaryaa to merge feature branch to develop
- [x] Iswaryaa to delete feature branch and close this issue

**Comment by kmohr-soprasteria** [comment]
![mapping](https://user-images.githubusercontent.com/57349523/203792219-9a07fa25-6e05-4aaf-b997-a670b9dd32b2.jpg)
